{ pkgs }:

let
  lib = pkgs.lib;

  # Stand-in drv: nixosOptionsDoc renders declarations, not values, so only
  # the attrs referenced by literal default expressions need to exist.
  placeholderDrv = {
    pname = "app";
    version = "0.0.0";
    meta = {
      description = "";
      longDescription = "";
      homepage = "";
      license = null;
    };
  };

  evaluated = lib.evalModules {
    modules = [
      ./schema.nix
      {
        _module.args = {
          drv = placeholderDrv;
          target = {
            arch = "x86_64";
            os = "linux";
          };
          format = "deb";
        };
      }
    ];
  };

  publicOptions = removeAttrs evaluated.options [ "_module" ];

  doc = pkgs.nixosOptionsDoc {
    options = publicOptions;
    # nixos-render-docs hardcodes nixpkgs as source-link base; drop the
    # `Declared by:` line so the rendered page doesn't point at a wrong repo.
    transformOptions =
      opt:
      opt
      // {
        declarations = [ ];
        visible = opt.visible && !(opt.internal or false);
      };
    warningsAreErrors = false;
  };

  header = pkgs.writeText "options-header.md" ''
    # `nix-bundle-app` — `info` options reference

    This file is **autogenerated** from [`lib/schema.nix`](../lib/schema.nix).
    Edit the schema and let the `docs` GitHub Actions workflow regenerate this page.

    ---

  '';
in
pkgs.runCommand "nix-bundle-app-docs"
  {
    meta.description = "Generated options reference for nix-bundle-app's info schema.";
  }
  ''
    out_dir=$out/share/doc/nix-bundle-app
    mkdir -p "$out_dir"

    cat ${header} ${doc.optionsCommonMark} > "$out_dir/options.md"
    cp ${doc.optionsJSON}/share/doc/nixos/options.json "$out_dir/options.json"
  ''
