{
  pkgs,
  lib,
  deps,
  utils,
  desktop,
  services,
  drv,
  format,
  meta,
  target,
}:

let
  common = import ./_common-linux.nix {
    inherit
      pkgs
      lib
      deps
      utils
      desktop
      services
      ;
  };
  pkgArch = meta.archArch;
  reqs = meta.depends.archlinux or [ ];
  optDeps = meta.depends.archlinuxOptional or [ ];

  installScript = lib.optionalString (common.hasServices meta) ''
    post_install() {
      ${common.postinstSnippet meta}
    }
    post_upgrade() {
      ${common.postinstSnippet meta}
    }
    pre_remove() {
      ${common.prermSnippet meta}
    }
    post_remove() {
      ${common.postrmSnippet meta}
    }
  '';
in
pkgs.stdenv.mkDerivation {
  name = "${meta.name}-${meta.version}-1-${pkgArch}.pkg.tar.zst";
  dontUnpack = true;
  nativeBuildInputs = with pkgs; [
    libarchive
    zstd
    gzip
    patchelf
    file
    gnugrep
    rsync
    coreutils
    gnused
    gawk
    findutils
  ];

  buildCommand = ''
    stage=$PWD/stage
    mkdir -p "$stage"

    ${common.stageLinux {
      inherit drv meta target;
      stage = "$stage";
    }}

    instSize=$(${pkgs.coreutils}/bin/du -sb "$stage" | ${pkgs.coreutils}/bin/cut -f1)
    builddate=$(date +%s)

    ${lib.optionalString meta.autoDepends (
      deps.discoverLinuxDepsSnippet {
        kind = "archlinux";
        scanDirs = [
          "$stage/opt/${meta.name}/bin"
          "$stage/opt/${meta.name}/lib"
        ];
        userDeps = reqs;
        outFile = "arch-depends.csv";
      }
    )}

    {
      echo "# Generated by nix-bundle-app"
      echo "pkgname = ${meta.name}"
      echo "pkgbase = ${meta.name}"
      echo "pkgver = ${meta.version}-1"
      echo "pkgdesc = ${meta.summary}"
      echo "url = ${meta.homepage}"
      echo "builddate = $builddate"
      echo "packager = ${meta.maintainer}"
      echo "size = $instSize"
      echo "arch = ${pkgArch}"
      echo "license = ${meta.license}"
      ${
        if meta.autoDepends then
          ''
            if [ -s arch-depends.csv ]; then
              tr ',' '\n' < arch-depends.csv | while read -r d; do
                [ -n "$d" ] && echo "depend = $d"
              done
            fi
          ''
        else
          lib.concatMapStrings (d: ''
            echo "depend = ${d}"
          '') reqs
      }
      ${lib.concatMapStrings (d: ''
        echo "optdepend = ${d}"
      '') optDeps}
    } > "$stage/.PKGINFO"

    ${lib.optionalString (common.hasServices meta) ''
      cp ${pkgs.writeText "${meta.name}.install" installScript} "$stage/.INSTALL"
      ${pkgs.gnused}/bin/sed -i 's/install = .*/&\ninstall = ${meta.name}.install/' "$stage/.PKGINFO" || true
    ''}

    (
      cd "$stage"
      LANG=C bsdtar -cf - --format=mtree \
        --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
        .PKGINFO * | ${pkgs.gzip}/bin/gzip -n -9 > .MTREE
    )

    mkdir -p $out
    out_pkg="$out/${meta.name}-${meta.version}-1-${pkgArch}.pkg.tar.zst"
    (
      cd "$stage"
      LANG=C bsdtar --no-fflags -cf - .PKGINFO .MTREE * \
        | ${pkgs.zstd}/bin/zstd -19 -T0 -o "$out_pkg"
    )

    cat > "$out/PKGBUILD" <<EOF
    # Maintainer: ${meta.maintainer}
    pkgname=${meta.name}
    pkgver=${meta.version}
    pkgrel=1
    pkgdesc='${meta.summary}'
    arch=('${pkgArch}')
    url='${meta.homepage}'
    license=('${meta.license}')
    depends=(${lib.concatMapStringsSep " " (d: "'" + d + "'") reqs})
    ${lib.optionalString (optDeps != [ ])
      "optdepends=(${lib.concatMapStringsSep " " (d: "'" + d + "'") optDeps})"
    }
    source=("${meta.name}-${meta.version}.tar.gz")
    sha256sums=('SKIP')

    package() {
      cp -r "\$srcdir/opt"     "\$pkgdir/" 2>/dev/null || true
      cp -r "\$srcdir/usr"     "\$pkgdir/" 2>/dev/null || true
      cp -r "\$srcdir/lib"     "\$pkgdir/" 2>/dev/null || true
    }
    EOF
    ${pkgs.gnused}/bin/sed -i 's/^    //' "$out/PKGBUILD"
  '';

  passthru = {
    info = meta;
    inherit target format;
  };
}
