{
  pkgs,
  lib,
  deps,
  utils,
  desktop,
  services,
  drv,
  format,
  meta,
  target,
}:

let
  common = import ./_common-linux.nix {
    inherit
      pkgs
      lib
      deps
      utils
      desktop
      services
      ;
  };
  pkgArch = meta.archArch;
  reqs = meta.depends.archlinux or [ ];
  optDeps = meta.depends.archlinuxOptional or [ ];

  aurPkgname = "${meta.name}-bin";
  aurTarName = "${aurPkgname}-${meta.version}-${pkgArch}.tar.gz";
  downloadUrl =
    if meta.downloadUrl != "" then meta.downloadUrl else "https://example.com/releases/${aurTarName}";

  installScript = lib.optionalString (common.hasServices meta) ''
    post_install() {
      ${common.postinstSnippet meta}
    }
    post_upgrade() {
      ${common.postinstSnippet meta}
    }
    pre_remove() {
      ${common.prermSnippet meta}
    }
    post_remove() {
      ${common.postrmSnippet meta}
    }
  '';

  depsArr = lib.concatMapStringsSep " " (d: "'" + d + "'") reqs;
  optDepsArr = lib.concatMapStringsSep " " (d: "'" + d + "'") optDeps;
in
pkgs.stdenv.mkDerivation {
  name = "${meta.name}-${meta.version}-1-${pkgArch}.pkg.tar.zst";
  dontUnpack = true;
  nativeBuildInputs = with pkgs; [
    libarchive
    zstd
    gzip
    gnutar
    patchelf
    file
    gnugrep
    rsync
    coreutils
    gnused
    gawk
    findutils
  ];

  buildCommand = ''
    stage=$PWD/stage
    mkdir -p "$stage"

    ${common.stageLinux {
      inherit drv meta target;
      stage = "$stage";
    }}

    instSize=$(${pkgs.coreutils}/bin/du -sb "$stage" | ${pkgs.coreutils}/bin/cut -f1)
    builddate=$(date +%s)

    ${lib.optionalString meta.autoDepends (
      deps.discoverLinuxDepsSnippet {
        kind = "archlinux";
        scanDirs = [
          "$stage/opt/${meta.name}/bin"
          "$stage/opt/${meta.name}/lib"
        ];
        userDeps = reqs;
        outFile = "arch-depends.csv";
      }
    )}

    {
      echo "# Generated by nix-bundle-app"
      echo "pkgname = ${meta.name}"
      echo "pkgbase = ${meta.name}"
      echo "pkgver = ${meta.version}-1"
      echo "pkgdesc = ${meta.summary}"
      echo "url = ${meta.homepage}"
      echo "builddate = $builddate"
      echo "packager = ${meta.maintainer}"
      echo "size = $instSize"
      echo "arch = ${pkgArch}"
      echo "license = ${meta.license}"
      ${
        if meta.autoDepends then
          ''
            if [ -s arch-depends.csv ]; then
              tr ',' '\n' < arch-depends.csv | while read -r d; do
                [ -n "$d" ] && echo "depend = $d"
              done
            fi
          ''
        else
          lib.concatMapStrings (d: ''
            echo "depend = ${d}"
          '') reqs
      }
      ${lib.concatMapStrings (d: ''
        echo "optdepend = ${d}"
      '') optDeps}
    } > "$stage/.PKGINFO"

    ${lib.optionalString (common.hasServices meta) ''
      cp ${pkgs.writeText "${meta.name}.install" installScript} "$stage/.INSTALL"
      ${pkgs.gnused}/bin/sed -i 's/install = .*/&\ninstall = ${meta.name}.install/' "$stage/.PKGINFO" || true
    ''}

    (
      cd "$stage"
      LANG=C bsdtar -cf - --format=mtree \
        --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
        .PKGINFO * | ${pkgs.gzip}/bin/gzip -n -9 > .MTREE
    )

    mkdir -p $out
    out_pkg="$out/${meta.name}-${meta.version}-1-${pkgArch}.pkg.tar.zst"
    (
      cd "$stage"
      LANG=C bsdtar --no-fflags -cf - .PKGINFO .MTREE * \
        | ${pkgs.zstd}/bin/zstd -19 -T0 -o "$out_pkg"
    )

    # AUR-publishable layout: a source tarball (bin-style payload) plus a
    # PKGBUILD that downloads it from `info.downloadUrl` + a generated
    # `.SRCINFO`. Push the trio to `aur:<pkgname>-bin.git`.
    aurDir=$out/aur
    mkdir -p "$aurDir"

    aurStage=$PWD/aur-stage
    mkdir -p "$aurStage"
    ( cd "$stage" && ${pkgs.coreutils}/bin/cp -a --no-preserve=ownership . "$aurStage/" )
    rm -f "$aurStage/.PKGINFO" "$aurStage/.MTREE" "$aurStage/.INSTALL"

    aurTar="$aurDir/${aurTarName}"
    ( cd "$aurStage" && ${pkgs.gnutar}/bin/tar --owner=0 --group=0 --sort=name \
        -czf "$aurTar" . )

    aurSha=$(${pkgs.coreutils}/bin/sha256sum "$aurTar" | ${pkgs.coreutils}/bin/cut -d' ' -f1)

    cat > "$aurDir/PKGBUILD" <<EOF
    # Maintainer: ${meta.maintainer}
    pkgname=${aurPkgname}
    _pkgname=${meta.name}
    pkgver=${meta.version}
    pkgrel=1
    pkgdesc='${meta.summary}'
    arch=('${pkgArch}')
    url='${meta.homepage}'
    license=('${meta.license}')
    depends=(${depsArr})
    ${lib.optionalString (optDeps != [ ]) "optdepends=(${optDepsArr})"}
    provides=("\''${_pkgname}=\''${pkgver}")
    conflicts=("\''${_pkgname}")
    source=("${downloadUrl}")
    sha256sums=("$aurSha")
    ${lib.optionalString (common.hasServices meta) "install=${aurPkgname}.install"}

    package() {
      cp -a "\$srcdir/opt"  "\$pkgdir/"  2>/dev/null || true
      cp -a "\$srcdir/usr"  "\$pkgdir/"  2>/dev/null || true
      cp -a "\$srcdir/lib"  "\$pkgdir/"  2>/dev/null || true
    }
    EOF
    ${pkgs.gnused}/bin/sed -i 's/^    //' "$aurDir/PKGBUILD"

    ${lib.optionalString (common.hasServices meta) ''
      cp ${pkgs.writeText "${aurPkgname}.install" installScript} "$aurDir/${aurPkgname}.install"
    ''}

    {
      echo "pkgbase = ${aurPkgname}"
      echo "	pkgdesc = ${meta.summary}"
      echo "	pkgver = ${meta.version}"
      echo "	pkgrel = 1"
      echo "	url = ${meta.homepage}"
      echo "	arch = ${pkgArch}"
      echo "	license = ${meta.license}"
      ${lib.concatMapStrings (d: ''
        echo "	depends = ${d}"
      '') reqs}
      ${lib.concatMapStrings (d: ''
        echo "	optdepends = ${d}"
      '') optDeps}
      echo "	provides = ${meta.name}=${meta.version}"
      echo "	conflicts = ${meta.name}"
      echo "	source = ${downloadUrl}"
      echo "	sha256sums = $aurSha"
      ${lib.optionalString (common.hasServices meta) ''
        echo "	install = ${aurPkgname}.install"
      ''}
      echo ""
      echo "pkgname = ${aurPkgname}"
    } > "$aurDir/.SRCINFO"

    # Drop the old local-source PKGBUILD; users should consume aur/ instead.
    rm -f "$out/PKGBUILD"
  '';

  passthru = {
    info = meta;
    inherit target format;
  };
}
